#!/usr/bin/env ruby

require "#{File.dirname(__FILE__)}/../j_thumb"
#####################################
# This scipt is run to setup the storage
# pass --init arguement to cleanup storage and start from scratch
#####################################
init = (ARGV[0] == '--init')
JThumb::Storage.setup(init)
